services:
  # ----------------------
  # 1) Postgres DB
  # ----------------------
  db:
    image: postgres:13
    container_name: ${COMPOSE_DB_NAME:-db}_instance
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${COMPOSE_DB_HOST_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      db_network:
        aliases:
          - ${COMPOSE_DB_NAME:-db}

volumes:
  db_data:
    external: true
    name: ${COMPOSE_DB_VOLUME_NAME:-db_data}

networks:
  db_network:
    external: true
    name: ${COMPOSE_NETWORK_NAME?Docker Compose Config Error! COMPOSE_NETWORK_NAME is not set!}
