services:
  # ----------------------
  # 1) Postgres DB
  # ----------------------
  db:
    image: postgres:13
    container_name: ${COMPOSE_DB_NAME:-db}_instance
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${COMPOSE_DB_HOST_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      db_network:
        aliases:
          - ${COMPOSE_DB_NAME:-db}
    profiles:
      - "${COMPOSE_PROFILE_DB_DEFAULT?Docker Compose Config Error! COMPOSE_PROFILE_DB_DEFAULT is not set!}"

  # ----------------------
  # 2) Database Migration Service
  # ----------------------
  migrate:
    build:
      context: .
      dockerfile: devops-toolkit/backend/docker/migrate.Dockerfile
      args:
        APP_NAME: ${APP_NAME?Docker Compose Config Error! APP_NAME is not set!}
        ENV: ${ENV?Docker Compose Config Error! ENV is not set!}
        HCP_ORG_ID: ${HCP_ORG_ID?Docker Compose Config Error! HCP_ORG_ID is not set!}
        HCP_PROJECT_ID: ${HCP_PROJECT_ID?Docker Compose Config Error! HCP_PROJECT_ID is not set!}
        HCP_ENCRYPTED_API_TOKEN: ${HCP_ENCRYPTED_API_TOKEN?Docker Compose Config Error! HCP_ENCRYPTED_API_TOKEN is not set!}
        MIGRATIONS_PATH: ${MIGRATIONS_PATH:-migrations}
    profiles:
      - "${COMPOSE_PROFILE_DB_DEFAULT?Docker Compose Config Error! COMPOSE_PROFILE_DB_DEFAULT is not set!}"
    networks:
      - db_network
    environment:
      HCP_TOKEN_ENC_KEY: ${HCP_TOKEN_ENC_KEY?Docker Compose Config Error! HCP_TOKEN_ENC_KEY is not set!}

volumes:
  db_data:
    external: true
    name: ${COMPOSE_DB_VOLUME_NAME:-db_data}

networks:
  db_network:
    external: true
    name: ${COMPOSE_NETWORK_NAME?Docker Compose Config Error! COMPOSE_NETWORK_NAME is not set!}
